Vuejs neomad
neomad-team/styleguide pull request #10
Opened 2017-09-13 15:21 UTC by vinyll

This PR is moving from defining styles in css to defining styles into components.

The components may then be called directly (ex: `<x-button>`) or transform a regular node (ex: `<a is=x-button>`).

It's currently implementing 2 elements:
- `x-button`
- `x-form` (with a `class=login` transformer)

2017-09-16 19:16 UTC, fuentesloic requested changes

2017-09-16 19:16 UTC, fuentesloic commented on demo/atoms.html
> +<script src=/dist/build.js></script>
src` should be `../dist/build.js`

2017-09-16 19:16 UTC, fuentesloic commented on demo/components.html
> +<script src=/dist/build.js></script>
src` should be `../dist/build.js`

2017-09-17 17:01 UTC, fuentesloic commented on demo/components.html
> +        <x-avatar src=https://neomad.org/static/uploads/avatars/5914dbdca193770016e289a7></x-avatar>
should be `<img is=x-avatar ...`

2017-09-17 17:01 UTC, fuentesloic commented on demo/components.html
> +  <x-menu>
same here should be `<nav is=x-menu>`

2017-09-17 17:01 UTC, fuentesloic commented on demo/components.html
> +    <x-avatar src=/static/uploads/avatars/5914dbdca193770016e289a7 alt=""></x-avatar>
again with `<img is=x-avatar ...`

2017-09-18 07:08 UTC, vinyll commented
I'm not sure about which approach to adopt for the demo folder.
Here I went for using the explicit tag name for easier comprehension, keeping in mind that for SEO purpose the components would probably be used with a html5 template and the `is=…` attribute.

Opinions are welcome regarding this.

2017-09-18 07:10 UTC, vinyll commented
Because the `/demo` folder and the `/dist` folder are totally decoupled (at the opposite of a `/static` folder that would hold all the js/css/images/fonts/…) I'd rather stick with an absolute path in this case. We may discuss about that.

2018-03-06 23:55 UTC, closed without merging