added makefile for deployment on neomad server
neomad-team/styleguide pull request #42
Opened 2018-08-20 14:37 UTC by vinyll

`make deploy` updates https://styleguide.neomad.org for those who have a neomad server access set up.

2018-08-20 15:12 UTC, fuentesloic approved these changes

2018-08-20 15:13 UTC, fuentesloic commented
@vinyll you have to pull `cirlceci` branch and merge it inside, right ?

2018-08-20 15:26 UTC, fuentesloic requested changes
@vinyll you have to pull `cirlceci` branch and merge it inside, right ?

2018-08-20 15:31 UTC, vinyll commented
> @vinyll you have to pull cirlceci branch and merge it inside, right ?

We don't _have to_, but it will be compliant.
Right now it works as is.

2018-08-20 23:56 UTC, fuentesloic commented
as is we can't merge this PR cause circleCI

2018-08-21 00:02 UTC, fuentesloic submitted a review, later dismissed

2018-08-21 01:25 UTC, fuentesloic commented
@vinyll could you review ?

2018-08-21 07:21 UTC, vinyll reviewed
I can't set a status as I'm the author of this PR.
You'll need to request your own changes!
(is this a Microsoft product to be so weird?! :p )

2018-08-21 07:21 UTC, vinyll commented on index.html
> +<meta http-equiv=refresh content="0; url=/content/00-index.html">
This should now be `…url=/content/index.html`

2018-08-21 07:24 UTC, vinyll commented
We couldn't merge but once the other PR was approved, this one would have been rebased and passed ;)
Someone else than me will be able to approve this PR.
But it the "index.html" must be resolved first!

2018-08-21 12:21 UTC, fuentesloic commented on index.html
> +<meta http-equiv=refresh content="0; url=/content/00-index.html">
true I forget the modif!

2018-08-21 12:25 UTC, fuentesloic approved these changes

2018-08-21 23:55 UTC, merged